
create database db_reserva_de_mesas;

\connect db_reserva_de_mesas

create table restaurante(
    id integer primary not null generated by default as entity,
    nombre text not null,
    direccion not null,
    max_X integer not null,
    max_Y integer not null
);

create table mesa(
    id integer primary key not null generated by default as entity,
    nombre_mesa text not null,
    id_restaurante integer not null,
    pos_x integer not null,
    pos_y integer not null,
    nro_piso integer not null
);

alter table mesa add constraint id_restaurante_fk_me foreign key(id_restaurante) references restaurante(id);

create table cliente(
    id integer primary key not null generated by default as entity,
    cedula integer not null unique,
    nombre text not null,
    apellido text not null
);

create table reserva(
    id integer primary key not null generated by default as entity,
    id_restaurante integer not null,
    id_mesa integer not null,
    fecha date not null,
    rango_hora text not null,
    id_cliente integer not null,
    cantidad_solicitada integer not null,
);

alter table reserva add constraint id_restaurante_fk_res foreign key(id_restaurante) references restaurante(id);
alter table reserva add constraint id_mesa_fk foreign key(id_mesa) references mesa(id);
alter table reserva add constraint id_cliente_fk foreign key(id_cliente) references cliente(id);

